### ISSUE TITLE
Is the meal pocket available?

### ISSUE THREAD

**Issue by naps62** [netsoft-ruidias/ha-custom-component-coverflex#2]
First of all, I was incredibly happy to see this show up on my top suggestions in HASS :smile: I worked a bit with Coverflex in the past, and currently use their card

Besides the benefits budget, does this currently support the meal budget (subsidio de alimentacao)? I have both on my card, but I was only able to import the benefits budget so far

**Comment by TiagoJVO** [comment]
Just fixed the issue, already asked @netsoft-ruidias to add me as a contributor so I can create a new branch to open a PR

**Comment by netsoft-ruidias** [comment]
Hi!

Please try [version 2](https://github.com/netsoft-ruidias/ha-custom-component-coverflex/releases/tag/v2), now with OTP (2FA) and some other improvements.
